const verbs = [
  { es: "Abanderar/Registrar", en: "To register" },
  { es: "Abrir", en: "To open" },
  { es: "Aburrir", en: "To bore" },
  { es: "Acabar", en: "To finish" },
  { es: "Aceptar", en: "To accept" },
  { es: "Acordar", en: "To do something" },
  { es: "Acostar", en: "To go to bed" },
  { es: "Almorzar", en: "To have lunch" },
  { es: "Amar", en: "To love" },
  { es: "Andar", en: "To walk" },
  { es: "Apagar", en: "Off – putout – extinguish" },
  { es: "Aprender", en: "To learn" },
  { es: "Asistir", en: "To assist – attend" },
  { es: "Ayudar", en: "To help" },
  { es: "Bailar", en: "To dance" },
  { es: "Bajar", en: "To go down – get off (bus)" },
  { es: "Beber", en: "To drink" },
  { es: "Buscar", en: "To look for" },
  { es: "Caber", en: "To fit" },
  { es: "Caer", en: "To fall" },
  { es: "Cambiar", en: "To change" },
  { es: "Cantar", en: "To sing" },
  { es: "Casar", en: "To marry / get married" },
  { es: "Cenar", en: "To have dinner, To have a evening meal." },
  { es: "Cerrar", en: "To close" },
  { es: "Cocinar", en: "To cook" },
  { es: "Coger", en: "To pick up / take / catch" },
  { es: "Comenzar", en: "To star / begin" },
  { es: "Comer", en: "To eat" },
  { es: "Compartir", en: "To share" },
  { es: "Comprar", en: "To buy" },
  { es: "Comprender", en: "To understand" },
  { es: "Conducir", en: "To driver" },
  { es: "Conocer", en: "To know" },
  { es: "Conseguir", en: "To obtein / fin" },
  { es: "Construir", en: "To build" },
  { es: "Contar", en: "To count / tell" },
  { es: "Corregir", en: "To correct" },
  { es: "Correr", en: "To run" },
  { es: "Cortar", en: "To cut" },
  { es: "Costar", en: "To cost" },
  { es: "Crear", en: "To create" },
  { es: "Crecer", en: "To grow" },
  { es: "Creer", en: "To think" },
  { es: "Cruzar", en: "To cross" },
  { es: "Cubrir", en: "To cover" },
  { es: "Dar", en: "To give" },
  { es: "Deber", en: "To must" },
  { es: "Decidir", en: "To decide" },
  { es: "Decir", en: "To say / tell" },
  { es: "Defender", en: "To defend / stand up for" },
  { es: "Dejar", en: "To leave" },
  { es: "Desayunar", en: "To have breakfast" },
  { es: "Descubrir", en: "To discover" },
  { es: "Desear", en: "To wish" },
  { es: "Despedir", en: "To say goodbye" },
  { es: "Despertar", en: "To wake up" },
  { es: "Destruir", en: "To destroy / wreck / demolish" },
  { es: "Devolver", en: "To return" },
  { es: "Dirigir", en: "To manage" },
  { es: "Divertir", en: "To entertain / have fun" },
  { es: "Doler", en: "to hurt" },
  { es: "Dormir", en: "To sleep" },
  { es: "Duchar", en: "To take a shower" },
  { es: "Echar", en: "To throw" },
  { es: "Elegir", en: "To choose" },
  { es: "Empezar", en: "To begin" },
  { es: "Encantar", en: "To love something" },
  { es: "Encender", en: "To light / turn on" },
  { es: "Encontrar", en: "To find" },
  { es: "Entender", en: "To understand" },
  { es: "Entrar", en: "To go in" },
  { es: "Enviar", en: "To send" },
  { es: "Escoger", en: "To choose" },
  { es: "Escribir", en: "To writte" },
  { es: "Escuchar", en: "To listen" },
  { es: "Esperar", en: "To wait" },
  { es: "Estar", en: "To be" },
  { es: "Estudiar", en: "To study" },
  { es: "Exigir", en: "To demand / require" },
  { es: "Explicar", en: "To explain" },
  { es: "Ganar", en: "To win" },
  { es: "Gastar", en: "To spend" },
  { es: "Gustar", en: "To like" },
  { es: "Haber", en: "To have" },
  { es: "Habilitar", en: "To fit out / authorise" },
  { es: "Habitar", en: "To inhabit" },
  { es: "Habituar", en: "To get used to" },
  { es: "Hablar", en: "To speak" },
  { es: "Hacer", en: "To make, to do" },
  { es: "Hackear", en: "To hack" },
  { es: "Halagar", en: "To flatter" },
  { es: "Hartar", en: "To get bored of" },
  { es: "Helar", en: "To freeze" },
  { es: "Henchir", en: "To fill" },
  { es: "Herir", en: "To hurt" },
  { es: "Hervir", en: "To boil" },
  { es: "Hinchar", en: "To swell" },
  { es: "Hospedar", en: "To provide accomodation" },
  { es: "Hostigar", en: "To bother, pester" },
  { es: "Huir", en: "To run away, to escape" },
  { es: "Incluir", en: "To include" },
  { es: "Ir", en: "To go" },
  { es: "Jugar", en: "To play" },
  { es: "Lavar", en: "To wash" },
  { es: "Leer", en: "To read" },
  { es: "Levantar", en: "To raise" },
  { es: "Limpiar", en: "To clean" },
  { es: "Llamar", en: "To call" },
  { es: "Llenar", en: "To fill" },
  { es: "Llegar", en: "To arrive" },
  { es: "Llevar", en: "To carry, wear" },
  { es: "Llorar", en: "To cry" },
  { es: "Llover", en: "To rain" },
  { es: "Mandar", en: "To order" },
  { es: "Manejar", en: "To handle, use, manage." },
  { es: "Mantener", en: "To maintain" },
  { es: "Medir", en: "To measure" },
  { es: "Mentir", en: "To lie" },
  { es: "Mirar", en: "To look at, wash" },
  { es: "Morir", en: "To die" },
  { es: "Mostrar", en: "To show" },
  { es: "Mover", en: "To move" },
  { es: "Nace", en: "To beborn" },
  { es: "Nadar", en: "To swim" },
  { es: "Necesitar", en: "To need" },
  { es: "Obtener", en: "To obtain, win, get." },
  { es: "Ofrecer", en: "To offer" },
  { es: "Oír", en: "To hear" },
  { es: "Oler", en: "To smell" },
  { es: "Olvidar", en: "To forget" },
  { es: "Organizar", en: "To organize" },
  { es: "Pagar", en: "To pay" },
  { es: "Parar", en: "To stop" },
  { es: "Parecer", en: "To look like, seem" },
  { es: "Pasar", en: "To pass" },
  { es: "Pedir", en: "To ask, ask for" },
  { es: "Pensar", en: "To think" },
  { es: "Perder", en: "To lose" },
  { es: "Permitir", en: "To allow" },
  { es: "Poder", en: "Be able to" },
  { es: "Poner", en: "To put" },
  { es: "Practicar", en: "To practise" },
  { es: "Preferir", en: "To prefer" },
  { es: "Preguntar", en: "To ask" },
  { es: "Preparar", en: "To prepare" },
  { es: "Prestar", en: "To lend" },
  { es: "Probar", en: "To taste, try, try on" },
  { es: "Proteger", en: "To protect" },
  { es: "Quedar", en: "To stay" },
  { es: "Quejar", en: "To complain" },
  { es: "Querer", en: "To want" },
  { es: "Quitar", en: "To take off" },
  { es: "Recibir", en: "To receive" },
  { es: "Recoger", en: "To pick up" },
  { es: "Recomendar", en: "To recommend" },
  { es: "Recordar", en: "To remember" },
  { es: "Regresar", en: "To go back, come back" },
  { es: "Reír", en: "To laugh" },
  { es: "Repetir", en: "To repeat" },
  { es: "Resolver", en: "to resolve" },
  { es: "Rogar", en: "To beg" },
  { es: "Romper", en: "To break" },
  { es: "Rezar", en: "To pray" },
  { es: "Remar", en: "To row" },
  { es: "Saber", en: "To know" },
  { es: "Sacar", en: "To take out" },
  { es: "Salir", en: "To go out" },
  { es: "Secar", en: "To dry" },
  { es: "Seguir", en: "To follow" },
  { es: "Sentar", en: "To sit, seat" },
  { es: "Sentir", en: "To feel" },
  { es: "Ser", en: "To be" },
  { es: "Servir", en: "To serve" },
  { es: "Sofreír", en: "To saute, fry." },
  { es: "Soler", en: "To ussually do something" },
  { es: "Sonar", en: "To sound" },
  { es: "Sonreír", en: "To smile" },
  { es: "Subir", en: "To go up, com up" },
  { es: "Sugerir", en: "To suggest" },
  { es: "Sumergir", en: "To inmerse, submerge, dip." },
  { es: "Tener", en: "To have" },
  { es: "Terminar", en: "To finish" },
  { es: "Tocar", en: "To touch" },
  { es: "Tomar", en: "To take" },
  { es: "Trabajar", en: "To work" },
  { es: "Traducir", en: "To translate" },
  { es: "Traer", en: "To bring" },
  { es: "Tratar", en: "To treat /try" },
  { es: "Usar", en: "To use" },
  { es: "Valer", en: "To be worth" },
  { es: "Velar", en: "To guard" },
  { es: "Vender", en: "To sale" },
  { es: "Venir", en: "To come" },
  { es: "Ver", en: "To see" },
  { es: "Vestir", en: "To wear, dress" },
  { es: "Viajar", en: "To travel" },
  { es: "Visitar", en: "To visit" },
  { es: "Vivir", en: "To live" },
  { es: "Volar", en: "To fly" },
  { es: "Volver", en: "To return" },
  { es: "Violar", en: "To violate" },
];

module.exports = {
  verbs,
};
